{% set name = "panflute" %}
{% set version = "2.1.0" %}
# inclusive
{% set pandoc_minimum_version = "2.11.0.4" %}
# exclusive
{% set pandoc_maximum_version = "2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/sergiocorreia/panflute/archive/refs/tags/2.1.0.tar.gz
  sha256: f9b57046354b3372fa97446d295f843ff51b59887f619163dc0cdf164e45a606

build:
  noarch: python
  number: 1
  entry_points:
    - panflute = panflute:main
    - panfl = panflute:panfl
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyyaml >=3,<6
    - click >=6,<8
  run_constrained:
    - pandoc >={{ pandoc_minimum_version }},<{{ pandoc_maximum_version }}

test:
  imports:
    - panflute
  commands:
    - pip check
    - |
      echo '# Testing' | pandoc -F panflute 
    - panfl --help
  requires:
    - pip
    - pandoc >={{ pandoc_minimum_version }},<{{ pandoc_maximum_version }}

about:
  home: https://github.com/sergiocorreia/panflute
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pythonic Pandoc filters
  doc_url: http://scorreia.com/software/panflute/
  dev_url: https://github.com/sergiocorreia/panflute

extra:
  recipe-maintainers:
    - ickc
    - kiwi0fruit
