{% set name = "panflute" %}
{% set version = "2.0.5" %}
{% set pandoc_minimum_version = "2.11.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff6b65624442ed4a331133326ca001f4043a6552e6d344e87dc085943dc355eb

build:
  noarch: python
  number: 0
  entry_points:
    - panflute = panflute:main
    - panfl = panflute:panfl
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyyaml
    - click
  run_constrained:
    - pandoc >={{ pandoc_minimum_version }}

test:
  imports:
    - panflute
  commands:
    - pip check
    - |
      echo '# Testing' | pandoc -F panflute 
    - panfl --help
  requires:
    - pip
    - pandoc >={{ pandoc_minimum_version }}

about:
  home: https://github.com/sergiocorreia/panflute
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pythonic Pandoc filters
  doc_url: http://scorreia.com/software/panflute/
  dev_url: https://github.com/sergiocorreia/panflute

extra:
  recipe-maintainers:
    - ickc
    - kiwi0fruit
