{% set name = "panflute" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66634558c13707032839d8795cd134dfcd43511409e82ab2f126295ebe7e249c

build:
  noarch: python
  number: 0
  entry_points:
    - panflute = panflute:main
    - panfl = panflute:panfl
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml
    - future
    - shutilwhich
    - click

test:
  imports:
    - panflute
  commands:
    - panfl --help

about:
  home: https://github.com/sergiocorreia/panflute
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pythonic Pandoc filters'
  doc_url: http://scorreia.com/software/panflute/
  dev_url: https://github.com/sergiocorreia/panflute

extra:
  recipe-maintainers:
    - kiwi0fruit
