travis:
  secure:
    BINSTAR_TOKEN: P6HKJVnQgB8+jRoLXa+2mpOgfvXsy1Zd0sKrIOZgOzycyBM0yx0WSblarmC8O+oot5HT9dtQDXpS/l/yZHYxwgmWWjgJqAUGypvPwZwkD6lWP5LRInfAdUlxBPoKNm510diJDvcDR/Iqw3lSGItG3/KwiARPabuoUc/t+dh7eOJrHgMbcnbU/ln7kYPGfTF5KfB4T0Zvx6B2PhddjFwM0fYrDkyqq5mL19z+boX3m/L8hFaE0FYUuwtSNEbrn3xgT0oZAchrPlU1Ta3Qfq2NXcsel+3khlmPAyH+IjZ88rI8FOQrkNrRyLG1HDXurzLbUG7/SODeev2qymGhPFplaXOprv0Dv1BGnidt/zg+8+2uqpYPibvHMzf/6ECG3b6ZtEjXAL4FzYbuG3dzzb7JzGZWaafU/5GgwIDhrhixE0rMzr6vLgVziAQBNgNHqq+dK3fjMs8tV/BJI7VPoqalVIbLbWdBDyjpNgLzksI8Rdy0u0GepScqfnf5AiPDUqbZ5tNsPiJbOtcHVhey4xvOFl3jkS3p7uvHDmDAePEdwFRCNjjgkx+CSSBXqh2B5p/SYdC/N41ePcSAi69cL9eFilszuBt4Qx/M2M5MhX6GC0sbvw1298adAeX7uQJzVnMvUWy9LrLklUNKdivAeLWdW1ZvUCpkkRF3ZbvoU+UEuUI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
